<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LogonAsAdmin</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d47cbbb2-1b83-438d-aa99-a7fddb250fb8</testSuiteGuid>
   <testCaseLink>
      <guid>718bd0d4-1431-445f-857e-0a99491db8f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01. Administrator/a. AdminCreatorMenu/i. NormalTest/01. Login Normal Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>14117eb7-d702-4556-a2f5-2d6c2143898c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01. Administrator/a. AdminCreatorMenu/i. NormalTest/02. Create User Normal Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>066dda85-2521-47d5-9013-3415c4de0b4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24ebc69b-bd78-4696-85da-89cb0ca57980</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1de92bf8-06b5-442a-bec9-93ccfb7cfdc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e609932-16df-4fdc-a283-bb0b2f80ba02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ae11334-fb45-4abc-8bc1-f0f6c7a6837c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fadee158-1457-44d4-a5e1-7546e7f9cddf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ccd9977-44ea-4316-8686-966aca6b0251</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5ebecd4-6ccf-4778-9b9e-c110b81dcca3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>991a442f-6c25-455d-9610-795bed47f173</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/99. Logoff</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
